version: '3'

services:
   backend:
      container_name: backend
      build: .
      ports:
         - '8000:8000'
      depends_on:
         - postgres
      env_file:
         - .env
      environment:
         QUERY_BATCH_SIZE: 32766
      # command: bash -c "yarn run dev"
      command: bash -c "yarn run dev"
      volumes:
         - .:/app
         - /app/node_modules
      restart: always
   postgres:
      container_name: postgres
      image: postgres:13-alpine
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: password4251
         POSTGRES_DB: notes-app-local
      ports:
         - '5432:5432'
      volumes:
         - note_db:/var/lib/postgresql/data

volumes:
   note_db: {}
