openapi: 3.0.0
info:
   title: Notes app API
   description: This is notes app API
   version: 1.0.0

servers:
   - url: http://localhost:8000/api
     description: Some

paths:
   /categories:
      get:
         summary: Get all categories
         tags:
            - Category
         parameters:
            - in: path
              name: user_id
              schema:
                 type: integer
                 required: true
                 description: Numeric user id
         responses:
            '200':
               description: OK
               content:
                  application/json:
                     schema:
                        type: array
                        items:
                           $ref: '#components/schemas/Category'
            '422':
               description: Validation error
               content:
                  application/json:
                     schema:
                        type: object
                        properties:
                           message:
                              type: string
                              example: Parameter type is invalid
   /category:
      title: category
      post:
         summary: Create category for notes
         tags:
            - Category
         requestBody:
            description: Category request body
            required: true
            content:
               application/json:
                  schema:
                     type: object
                     properties:
                        name:
                           type: string
                           example: Education
                        user_id:
                           type: number
                           example: 1
                     required:
                        - name
                        - user_id
         responses:
            '201':
               description: id of created category
               content:
                  application/json:
                     schema:
                        type: object
                        properties:
                           id:
                              type: number
                              description: created category id
                              example: 123
            '409':
               description:
               content:
                  application/json:
                     schema:
                        type: object
                        properties:
                           message:
                              type: string
                              example: Category already exists
            '422':
               description: invalid request body
               content:
                  application/json:
                     schema:
                        type: object
                        properties:
                           message:
                              type: string
                              example: Invalid request body
            '500':
               description: unexpected error
               content:
                  application/json:
                     schema:
                        type: object
                        properties:
                           message:
                              type: string
                              example: Someting went wrong
   /category/{id}:
      title: category
      put:
         summary: Update category
         tags:
            - Category
         requestBody:
            description: Category fields to be updated
            content:
               application/json:
                  schema:
                     type: object
                     properties:
                        name:
                           type: string
                           example: 'Education'
                        required:
                           - name
         responses:
            '200':
               description: Updated category
               content:
                  application/json:
                     schema:
                        type: object
                        properties:
                           id:
                              type: integer
                              description: ID of updated category
                              example: 1
                           name:
                              type: string
                              description: Updated name of category
                              example: Art
            '404':
               description: Category does not exist
               content:
                  application/json:
                     schema:
                        type: object
                        properties:
                           message:
                              type: string
                              description: Category with ID doesn't exist
                              example: Category does not exist
            '422':
               description: Invalid request body
               content:
                  application/json:
                     schema:
                        oneOf:
                           - $ref: '#components/schemas/InvalidRequestBodyError'
                           - $ref: '#components/schemas/InvalidRequestBodyFieldType'

      delete:
         summary: Delete category by "id"
         tags:
            - Category
         parameters:
            - in: path
              name: id
              schema:
                 type: integer
              required: true
              description: Numeric id of category
         responses:
            '200':
               description: successfully deleted category
               content:
                  application/json:
                     schema:
                        type: object
                        properties:
                           id:
                              type: integer
                              description: ID of deleted category
                              example: 1
            '404':
               description: Category ID is not found, cannot delete
               content:
                  application/json:
                     schema:
                        type: object
                        properties:
                           message:
                              type: string
                              example: Category does not exist

            '422':
               description: validation error
               content:
                  application/json:
                     schema:
                        type: object
                        properties:
                           message:
                              type: string
                              example: Parameter type is invalid

components:
   schemas:
      Category:
         type: object
         properties:
            id:
               type: number
               example: 1
            name:
               type: string
               example: Education
            created_at:
               type: string
               example: '2022-10-11T11:17:33.397Z'
      InvalidRequestBodyError:
         type: object
         properties:
            message:
               type: string
               example: Invalid request body
      InvalidRequestBodyFieldType:
         type: object
         properties:
            message:
               type: string
               example: One of fields has incorrect type
